# This file has been generated by node2nix 1.11.1. Do not edit!

{ nodeEnv, fetchurl, globalBuildInputs ? [ ], ... }:

let
  sources = {
    "prettier-2.8.3" = {
      name = "prettier";
      packageName = "prettier";
      version = "2.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-2.8.3.tgz";
        sha512 = "tJ/oJ4amDihPoufT5sM0Z1SKEuKay8LfVAMlbbhnnkvt6BUserZylqo2PN+p9KeljLr0OHa2rXHU1T8reeoTrw==";
      };
    };
    "svelte-3.55.1" = {
      name = "svelte";
      packageName = "svelte";
      version = "3.55.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte/-/svelte-3.55.1.tgz";
        sha512 = "S+87/P0Ve67HxKkEV23iCdAh/SX1xiSfjF1HOglno/YTbSTW7RniICMCofWGdJJbdjw3S+0PfFb1JtGfTXE0oQ==";
      };
    };
  };
in
{
  prettier = nodeEnv.buildNodePackage {
    name = "prettier";
    packageName = "prettier";
    version = "2.8.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier/-/prettier-2.8.3.tgz";
      sha512 = "tJ/oJ4amDihPoufT5sM0Z1SKEuKay8LfVAMlbbhnnkvt6BUserZylqo2PN+p9KeljLr0OHa2rXHU1T8reeoTrw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier is an opinionated code formatter";
      homepage = "https://prettier.io";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-svelte = nodeEnv.buildNodePackage {
    name = "prettier-plugin-svelte";
    packageName = "prettier-plugin-svelte";
    version = "2.9.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-svelte/-/prettier-plugin-svelte-2.9.0.tgz";
      sha512 = "3doBi5NO4IVgaNPtwewvrgPpqAcvNv0NwJNflr76PIGgi9nf1oguQV1Hpdm9TI2ALIQVn/9iIwLpBO5UcD2Jiw==";
    };
    dependencies = [
      sources."prettier-2.8.3"
      sources."svelte-3.55.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Svelte plugin for prettier";
      homepage = "https://github.com/sveltejs/prettier-plugin-svelte#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
