---
kind: pipeline
type: exec
name: deploy_boot ws1

platform:
  os: linux
  arch: amd64

steps:
- name: fetch submodules
  commands:
  - git submodule update --init --recursive --remote

- name: deploy_boot ws1
  commands:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - $(nix-build --no-out-link krops.nix --argstr name ws1 --argstr starget root@ws1.host.nerdworks.de --arg secrets false --arg home-manager true -A deploy_boot -I /var/src)
  environment:
    SSH_KEY:
      from_secret: ssh-key

...
