kind: pipeline
type: docker
name: default

steps:
  - name: push vim to cachix
    image: nixos/nix
    commands:
      - nix-channel --add https://nixos.org/channels/nixos-19.09 nixpkgs
      - nix-channel --update
      - nix-env -i cachix
      - nix-build -E 'with import <nixpkgs> {}; callPackage ./5pkgs/vim-customized {}' | cachix push nerdworks
    environment:
      CACHIX_SIGNING_KEY:
        from_secret: cachix-signing-key

