---
kind: pipeline
type: exec
name: deploy htz1

platform:
  os: linux
  arch: amd64

steps:
- name: fetch submodules
  commands:
  - git submodule update --init --recursive --remote

- name: deploy htz1
  commands:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - $(nix-build --no-out-link krops.nix --argstr name htz1 --arg secrets false --arg unstable true --arg mailserver false -A deploy -I /var/src)
  environment:
    SSH_KEY:
      from_secret: ssh-key

---
kind: pipeline
type: exec
name: deploy htz2

platform:
  os: linux
  arch: amd64

steps:
- name: fetch submodules
  commands:
  - git submodule update --init --recursive --remote

- name: deploy htz2
  commands:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - $(nix-build --no-out-link krops.nix --argstr name htz2 --arg secrets false --arg unstable true --arg mailserver true -A deploy -I /var/src)
  environment:
    SSH_KEY:
      from_secret: ssh-key

---
kind: pipeline
type: exec
name: deploy nas1

platform:
  os: linux
  arch: amd64

steps:
- name: fetch submodules
  commands:
  - git submodule update --init --recursive --remote

- name: deploy nas1
  commands:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - $(nix-build --no-out-link krops.nix --argstr name nas1 --arg secrets false --arg unstable false --arg mailserver false -A deploy -I /var/src)
  environment:
    SSH_KEY:
      from_secret: ssh-key

---
kind: pipeline
type: exec
name: deploy ws1

platform:
  os: linux
  arch: amd64

steps:
- name: fetch submodules
  commands:
  - git submodule update --init --recursive --remote

- name: deploy ws1
  commands:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - $(nix-build --no-out-link krops.nix --argstr name ws1 --arg secrets false --arg unstable true --arg mailserver false -A deploy -I /var/src)
  environment:
    SSH_KEY:
      from_secret: ssh-key

...
