---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  commands:
  - git submodule update --init --recursive --remote

- name: deploy apu1
  commands:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - $(nix-build --no-out-link krops.nix --argstr name apu1 --arg secrets false --arg unstable false -A deploy -I /var/src)
  environment:
    SSH_KEY:
      from_secret: ssh-key

- name: deploy htz1
  commands:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - $(nix-build --no-out-link krops.nix --argstr name htz1 --arg secrets false --arg unstable true -A deploy -I /var/src)
  environment:
    SSH_KEY:
      from_secret: ssh-key

- name: deploy htz2
  commands:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - $(nix-build --no-out-link krops.nix --argstr name htz2 --arg secrets false --arg unstable false -A deploy -I /var/src)
  environment:
    SSH_KEY:
      from_secret: ssh-key

- name: deploy nas1
  commands:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - $(nix-build --no-out-link krops.nix --argstr name nas1 --arg secrets false --arg unstable false -A deploy -I /var/src)
  environment:
    SSH_KEY:
      from_secret: ssh-key

- name: deploy nuc1
  commands:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - $(nix-build --no-out-link krops.nix --argstr name nuc1 --arg secrets false --arg unstable false -A deploy -I /var/src)
  environment:
    SSH_KEY:
      from_secret: ssh-key

...
