---
kind: pipeline
type: docker
name: cachix:burrow:nixos-19.09

platform:
  os: linux
  arch: amd64

steps:
- name: cachix:burrow:nixos-19.09
  image: nixos/nix
  commands:
  - nix-channel --add https://nixos.org/channels/nixos-19.09 nixpkgs
  - nix-channel --update
  - nix-env -i cachix
  - nix-build -E 'with import <nixpkgs> {}; callPackage ./5pkgs/burrow {}' | cachix push nerdworks
  environment:
    CACHIX_SIGNING_KEY:
      from_secret: cachix-signing-key

---
kind: pipeline
type: docker
name: cachix:burrow:nixos-unstable

platform:
  os: linux
  arch: amd64

steps:
- name: cachix:burrow:nixos-unstable
  image: nixos/nix
  commands:
  - nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
  - nix-channel --update
  - nix-env -i cachix
  - nix-build -E 'with import <nixpkgs> {}; callPackage ./5pkgs/burrow {}' | cachix push nerdworks
  environment:
    CACHIX_SIGNING_KEY:
      from_secret: cachix-signing-key

---
kind: pipeline
type: docker
name: cachix:vim-customized:nixos-19.09

platform:
  os: linux
  arch: amd64

steps:
- name: cachix:vim-customized:nixos-19.09
  image: nixos/nix
  commands:
  - nix-channel --add https://nixos.org/channels/nixos-19.09 nixpkgs
  - nix-channel --update
  - nix-env -i cachix
  - nix-build -E 'with import <nixpkgs> {}; callPackage ./5pkgs/vim-customized {}' | cachix push nerdworks
  environment:
    CACHIX_SIGNING_KEY:
      from_secret: cachix-signing-key

---
kind: pipeline
type: docker
name: cachix:vim-customized:nixos-unstable

platform:
  os: linux
  arch: amd64

steps:
- name: cachix:vim-customized:nixos-unstable
  image: nixos/nix
  commands:
  - nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
  - nix-channel --update
  - nix-env -i cachix
  - nix-build -E 'with import <nixpkgs> {}; callPackage ./5pkgs/vim-customized {}' | cachix push nerdworks
  environment:
    CACHIX_SIGNING_KEY:
      from_secret: cachix-signing-key

...
