default:
  tags:
  - docker-images

image: nixpkgs/nix-flakes:latest

before_script:
  - nix build .#cachix -o cachix
  - ./cachix/bin/cachix use fraam

build art:
  stage: build
  script:
  - nix build .#art -o art
  - ./cachix/bin/cachix push fraam art

build ffmpeg:
  stage: build
  script:
  - nix build .#ffmpeg -o ffmpeg
  - ./cachix/bin/cachix push fraam ffmpeg

# build hass-bs53:
#   stage: build
#   script:
#   - nix build .#hass-bs53 -o hass-bs53
#   - ./cachix/bin/cachix push hass-bs53 hass-bs53

#build eee1:
#  stage: build
#  script:
#  - nix build .#nixosConfigurations.eee1.config.system.build.toplevel
#  - ./cachix/bin/cachix push fraam result

#build tp1:
#  stage: build
#  script:
#  - nix build .#nixosConfigurations.tp1.config.system.build.toplevel
#  - ./cachix/bin/cachix push fraam result
