default:
  tags:
  - docker-images

image: nixpkgs/nix-flakes:latest

before_script:
  - nix build .#cachix -o cachix
  - ./cachix/bin/cachix use fraam

build art:
  stage: build
  script:
  - nix build .#art -o art
  - ./cachix/bin/cachix push fraam art

build ffmpeg:
  stage: build
  script:
  - nix build .#ffmpeg -o ffmpeg
  - ./cachix/bin/cachix push fraam ffmpeg

# build hass-bs53:
#   stage: build
#   script:
#   - nix build .#hass-bs53 -o hass-bs53
#   - ./cachix/bin/cachix push hass-bs53 hass-bs53

#build eee1:
#  stage: build
#  script:
#  - nix build .#nixosConfigurations.eee1.config.system.build.toplevel
#  - ./cachix/bin/cachix push fraam result

#build tp1:
#  stage: build
#  script:
#  - nix build .#nixosConfigurations.tp1.config.system.build.toplevel
#  - ./cachix/bin/cachix push fraam result

check apu2:
  stage: build
  script:
  - nix eval .#nixosConfigurations.apu2.config.system.build.toplevel.drvPath

check eee1:
  stage: build
  script:
  - nix eval .#nixosConfigurations.eee1.config.system.build.toplevel.drvPath

check htz1:
  stage: build
  script:
  - nix eval .#nixosConfigurations.htz1.config.system.build.toplevel.drvPath

check htz2:
  stage: build
  script:
  - nix eval .#nixosConfigurations.htz2.config.system.build.toplevel.drvPath

# fraamdb src missing
# check htz3:
#   stage: build
#   script:
#   - nix eval .#nixosConfigurations.htz3.config.system.build.toplevel.drvPath

check nas1:
  stage: build
  script:
  - nix eval .#nixosConfigurations.nas1.config.system.build.toplevel.drvPath

# frix missing
# check tp1:
#   stage: build
#   script:
#   - nix eval .#nixosConfigurations.tp1.config.system.build.toplevel.drvPath
# 
# check ws1:
#   stage: build
#   script:
#   - nix eval .#nixosConfigurations.ws1.config.system.build.toplevel.drvPath
# 
# check ws2:
#   stage: build
#   script:
#   - nix eval .#nixosConfigurations.ws2.config.system.build.toplevel.drvPath
