default:
  tags:
  - docker-images

image: nixpkgs/nix-flakes:latest

before_script:
  - nix build .#cachix -o cachix
  - ./cachix/bin/cachix use fraam

build tp1:
  stage: build
  script:
  - nix build .#nixosConfigurations.tp1.config.system.build.toplevel
  - ./cachix/bin/cachix push fraam result
