_:
{
  imports = [
    ./acme-dns.nix
    ./alertmanager-bot.nix
    ./cups-airprint.nix
    ./drone-server.nix
    ./fraam-gitlab.nix
    ./fraam-www.nix
    ./mjpg-streamer.nix
    ./nobbofin-autofetch.nix
    ./nwbackup.nix
    ./nwbackup-server.nix
    ./nwbitwarden.nix
    ./nwlogrotate.nix
    ./nwmonit.nix
    ./nwsyncthing.nix
    ./nwtraefik.nix
    ./octoprint.nix
    ./radicale.nix
    ./samba-sonos.nix
    ./secrets.nix
    ./traefik-forward-auth.nix
    ./vdi-container.nix
    ./wireguard.nix
    ./xrdp.nix
  ];
}
