_:
{
  imports = [
    ./acme-dns.nix
    ./alertmanager-bot.nix
    ./cups-airprint.nix
    ./drone-server.nix
    ./fluent-bit.nix
    ./kanboard.nix
    ./mautrix-whatsapp.nix
    ./minimal.nix
    ./mjpg-streamer.nix
    ./monica.nix
    ./mosquitto.nix
    ./motion.nix
    ./navidrome.nix
    ./neovim.nix
    ./nvidia.nix
    ./nwacme.nix
    ./nwbackup.nix
    ./nwbackup-server.nix
    ./nwbitwarden.nix
    ./nwlogrotate.nix
    ./nwsyncthing.nix
    ./nwtraefik.nix
    ./octoprint.nix
    ./photoprism.nix
    ./ports.nix
    ./radicale.nix
    ./rclone.nix
    ./samba-sonos.nix
    ./secrets.nix
    ./tor-ssh.nix
    ./traefik-forward-auth.nix
    ./traggo.nix
    ./vdi-container.nix
    ./wireguard.nix
    ./xrdp.nix
  ];
}
