_:
{
  imports = [
    ./fluent-bit.nix
    ./icloudpd.nix
    ./kanboard.nix
    ./mjpg-streamer.nix
    ./monica.nix
    ./navidrome.nix
    ./nvidia.nix
    ./nwbackup-server.nix
    ./nwbackup.nix
    ./nwlogrotate.nix
    ./nwsyncthing.nix
    ./oauth2-proxy.nix
    ./octoprint.nix
    ./photoprism.nix
    ./ports.nix
    ./radicale.nix
    ./rclone.nix
    ./secrets.nix
    ./tailscale.nix
    ./wireguard.nix
  ];
}
