# This file has been generated by node2nix 1.11.1. Do not edit!

{ nodeEnv, fetchurl, fetchgit, globalBuildInputs ? [ ], ... }:

let
  sources = {
    "@logseq/nbb-logseq-0.3.99" = {
      name = "_at_logseq_slash_nbb-logseq";
      packageName = "@logseq/nbb-logseq";
      version = "0.3.99";
      src = fetchurl {
        url = "https://registry.npmjs.org/@logseq/nbb-logseq/-/nbb-logseq-0.3.99.tgz";
        sha512 = "Msa6Ck6wqt7sYGExQZgUT/uUG/z5jGaPlytVdgGkCrVogZb2yaChbWeMOCfCsCTi6kbHo15hC3aOeDAXcfnFzw==";
      };
    };
    "builtins-4.1.0" = {
      name = "builtins";
      packageName = "builtins";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtins/-/builtins-4.1.0.tgz";
        sha512 = "1bPRZQtmKaO6h7qV1YHXNtr6nCK28k0Zo95KM4dXfILcZZwoHJBN1m3lfLv9LPkcOZlrSr+J1bzMaZFO98Yq0w==";
      };
    };
    "import-meta-resolve-1.1.1" = {
      name = "import-meta-resolve";
      packageName = "import-meta-resolve";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-meta-resolve/-/import-meta-resolve-1.1.1.tgz";
        sha512 = "JiTuIvVyPaUg11eTrNDx5bgQ/yMKMZffc7YSjvQeSMXy58DO2SQ8BtAf3xteZvmzvjYh14wnqNjL8XVeDy2o9A==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "semver-7.3.7" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.7.tgz";
        sha512 = "QlYTucUYOews+WeEujDoEGziz4K6c47V/Bd+LjSSYcA94p+DmINdf7ncaUinThfvZyu13lN9OY1XDxt8C0Tw0g==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
in
{
  "logseq-query-git+https://github.com/cldwalker/logseq-query.git#v0.9.0" = nodeEnv.buildNodePackage {
    name = "logseq-query";
    packageName = "logseq-query";
    version = "0.9.0";
    src = fetchgit {
      url = "https://github.com/cldwalker/logseq-query.git";
      rev = "a1796073d43d76af16f23d478086922915216425";
      sha256 = "005e71101e49877b4aa5faaa392c7df2898b725e6f90d68dddf98cccfed87564";
    };
    dependencies = [
      sources."@logseq/nbb-logseq-0.3.99"
      sources."builtins-4.1.0"
      sources."import-meta-resolve-1.1.1"
      sources."lru-cache-6.0.0"
      sources."semver-7.3.7"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Query logseq graphs easily";
      license = "MIT";
    };
    production = false;
    bypassCache = true;
    reconstructLock = true;
  };
}
