# This file has been generated by node2nix 1.11.1. Do not edit!

{ nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? [ ] }:

let
  sources = {
    "@ampproject/remapping-2.2.1" = {
      name = "_at_ampproject_slash_remapping";
      packageName = "@ampproject/remapping";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.2.1.tgz";
        sha512 = "lFMjJTrFL3j7L9yBxwYfCq2k6qqwHyzuUl/XBnif78PWTJYyL/dfowQHWE3sp6U6ZzqWiiIZnpTMO96zhkjwtg==";
      };
    };
    "@chevrotain/cst-dts-gen-11.0.3" = {
      name = "_at_chevrotain_slash_cst-dts-gen";
      packageName = "@chevrotain/cst-dts-gen";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/cst-dts-gen/-/cst-dts-gen-11.0.3.tgz";
        sha512 = "BvIKpRLeS/8UbfxXxgC33xOumsacaeCKAjAeLyOn7Pcp95HiRbrpl14S+9vaZLolnbssPIUuiUd8IvgkRyt6NQ==";
      };
    };
    "@chevrotain/gast-11.0.3" = {
      name = "_at_chevrotain_slash_gast";
      packageName = "@chevrotain/gast";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/gast/-/gast-11.0.3.tgz";
        sha512 = "+qNfcoNk70PyS/uxmj3li5NiECO+2YKZZQMbmjTqRI3Qchu8Hig/Q9vgkHpI3alNjr7M+a2St5pw5w5F6NL5/Q==";
      };
    };
    "@chevrotain/regexp-to-ast-11.0.3" = {
      name = "_at_chevrotain_slash_regexp-to-ast";
      packageName = "@chevrotain/regexp-to-ast";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/regexp-to-ast/-/regexp-to-ast-11.0.3.tgz";
        sha512 = "1fMHaBZxLFvWI067AVbGJav1eRY7N8DDvYCTwGBiE/ytKBgP8azTdgyrKyWZ9Mfh09eHWb5PgTSO8wi7U824RA==";
      };
    };
    "@chevrotain/types-11.0.3" = {
      name = "_at_chevrotain_slash_types";
      packageName = "@chevrotain/types";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/types/-/types-11.0.3.tgz";
        sha512 = "gsiM3G8b58kZC2HaWR50gu6Y1440cHiJ+i3JUvcp/35JchYejb2+5MVeJK0iKThYpAa/P2PYFV4hoi44HD+aHQ==";
      };
    };
    "@chevrotain/utils-11.0.3" = {
      name = "_at_chevrotain_slash_utils";
      packageName = "@chevrotain/utils";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/utils/-/utils-11.0.3.tgz";
        sha512 = "YslZMgtJUyuMbZ+aKvfF3x1f5liK4mWNxghFRv7jqRR9C3R3fAOGTTKvxXDa2Y1s9zSbcpuO0cAxDYsc9SrXoQ==";
      };
    };
    "@jridgewell/gen-mapping-0.3.3" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.3.tgz";
        sha512 = "HLhSWOLRi875zjjMG/r+Nv0oCW8umGb0BgEhyX3dDX3egwZtB8PqLnjz3yedt8R5StBrzcg4aBpnh8UA9D1BoQ==";
      };
    };
    "@jridgewell/resolve-uri-3.1.1" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.1.tgz";
        sha512 = "dSYZh7HhCDtCKm4QakX0xFpsRDqjjtZf/kjI/v3T3Nwt5r8/qz/M19F9ySyOqU94SXBmeG9ttTul+YnR4LOxFA==";
      };
    };
    "@jridgewell/set-array-1.1.2" = {
      name = "_at_jridgewell_slash_set-array";
      packageName = "@jridgewell/set-array";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/set-array/-/set-array-1.1.2.tgz";
        sha512 = "xnkseuNADM0gt2bs+BvhO0p78Mk762YnZdsuzFV018NoG1Sj1SCQvpSqa7XUaTam5vAGasABV9qXASMKnFMwMw==";
      };
    };
    "@jridgewell/sourcemap-codec-1.4.15" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.4.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.4.15.tgz";
        sha512 = "eF2rxCRulEKXHTRiDrDy6erMYWqNw4LPdQ8UQA4huuxaQsVeRPFl2oM8oDGxMFhJUWZf9McpLtJasDDZb/Bpeg==";
      };
    };
    "@jridgewell/trace-mapping-0.3.19" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.19.tgz";
        sha512 = "kf37QtfW+Hwx/buWGMPcR60iF9ziHa6r/CZJIHbmcm4+0qrXiVdxegAH0F6yddEVQ7zdkjcGCgCzUu+BcbhQxw==";
      };
    };
    "@toml-tools/lexer-1.0.0" = {
      name = "_at_toml-tools_slash_lexer";
      packageName = "@toml-tools/lexer";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@toml-tools/lexer/-/lexer-1.0.0.tgz";
        sha512 = "rVoOC9FibF2CICwCBWQnYcjAEOmLCJExer178K2AsY0Nk9FjJNVoVJuR5UAtuq42BZOajvH+ainf6Gj2GpCnXQ==";
      };
    };
    "@toml-tools/parser-1.0.0" = {
      name = "_at_toml-tools_slash_parser";
      packageName = "@toml-tools/parser";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@toml-tools/parser/-/parser-1.0.0.tgz";
        sha512 = "j8cd3A3ccLHppGoWI69urbiVJslrpwI6sZ61ySDUPxM/FTkQWRx/JkkF8aipnl0Ds0feWXyjyvmWzn70mIohYg==";
      };
    };
    "@types/estree-1.0.2" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.2.tgz";
        sha512 = "VeiPZ9MMwXjO32/Xu7+OwflfmeoRwkE/qzndw42gGtgJwZopBnzy2gD//NN1+go1mADzkDcqf/KnFRSjTJ8xJA==";
      };
    };
    "@xml-tools/parser-1.0.11" = {
      name = "_at_xml-tools_slash_parser";
      packageName = "@xml-tools/parser";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xml-tools/parser/-/parser-1.0.11.tgz";
        sha512 = "aKqQ077XnR+oQtHJlrAflaZaL7qZsulWc/i/ZEooar5JiWj1eLt0+Wg28cpa+XLney107wXqneC+oG1IZvxkTA==";
      };
    };
    "acorn-8.10.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.10.0.tgz";
        sha512 = "F0SAmZ8iUtS//m8DmCTA0jlh6TDKkHQyK6xc6V4KDTyZKA9dnvX9/3sRTVQrWm79glUAZbnmmNcdYwUIHWVybw==";
      };
    };
    "aria-query-5.3.0" = {
      name = "aria-query";
      packageName = "aria-query";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aria-query/-/aria-query-5.3.0.tgz";
        sha512 = "b0P0sZPKtyu8HkeRAfCq0IfURZK+SuwMjY1UXGBU27wpAiTwQAIlq56IbIO+ytk/JjS1fMR14ee5WBBfKi5J6A==";
      };
    };
    "axobject-query-3.2.1" = {
      name = "axobject-query";
      packageName = "axobject-query";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/axobject-query/-/axobject-query-3.2.1.tgz";
        sha512 = "jsyHu61e6N4Vbz/v18DHwWYKK0bSWLqn47eeDSKPB7m8tqMHF9YJ+mhIk2lVteyZrY8tnSj/jHOv4YiTCuCJgg==";
      };
    };
    "chevrotain-11.0.3" = {
      name = "chevrotain";
      packageName = "chevrotain";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chevrotain/-/chevrotain-11.0.3.tgz";
        sha512 = "ci2iJH6LeIkvP9eJW6gpueU8cnZhv85ELY8w8WiFtNjMHA5ad6pQLaJo9mEly/9qUyCpvqX8/POVUTf18/HFdw==";
      };
    };
    "chevrotain-7.1.1" = {
      name = "chevrotain";
      packageName = "chevrotain";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chevrotain/-/chevrotain-7.1.1.tgz";
        sha512 = "wy3mC1x4ye+O+QkEinVJkPf5u2vsrDIYW9G7ZuwFl6v/Yu0LwUuT2POsb+NUWApebyxfkQq6+yDfRExbnI5rcw==";
      };
    };
    "code-red-1.0.4" = {
      name = "code-red";
      packageName = "code-red";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-red/-/code-red-1.0.4.tgz";
        sha512 = "7qJWqItLA8/VPVlKJlFXU+NBlo/qyfs39aJcuMT/2ere32ZqvF5OSxgdM5xOfJJ7O429gg2HM47y8v9P+9wrNw==";
      };
    };
    "css-tree-2.3.1" = {
      name = "css-tree";
      packageName = "css-tree";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-tree/-/css-tree-2.3.1.tgz";
        sha512 = "6Fv1DV/TYw//QF5IzQdqsNDjx/wc8TrMBZsqjL9eW01tWb7R7k/mq+/VXfJCl7SoD5emsJop9cOByJZfs8hYIw==";
      };
    };
    "dequal-2.0.3" = {
      name = "dequal";
      packageName = "dequal";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dequal/-/dequal-2.0.3.tgz";
        sha512 = "0je+qPKHEMohvfRTCEo3CrPG6cAzAYgmzKyxRiYSSDkS6eGJdyVJm7WaYA5ECaAD9wLB2T4EEeymA5aFVcYXCA==";
      };
    };
    "estree-walker-3.0.3" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-3.0.3.tgz";
        sha512 = "7RUKfXgSMMkzt6ZuXmqapOurLGPPfgj6l9uRZ7lRGolvk0y2yocc35LdcxKC5PQZdn2DMqioAQ2NoWcrTKmm6g==";
      };
    };
    "is-reference-3.0.2" = {
      name = "is-reference";
      packageName = "is-reference";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-reference/-/is-reference-3.0.2.tgz";
        sha512 = "v3rht/LgVcsdZa3O2Nqs+NMowLOxeOm7Ay9+/ARQ2F+qEoANRcqrjAZKGN0v8ymUetZGgkp26LTnGT7H0Qo9Pg==";
      };
    };
    "locate-character-3.0.0" = {
      name = "locate-character";
      packageName = "locate-character";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-character/-/locate-character-3.0.0.tgz";
        sha512 = "SW13ws7BjaeJ6p7Q6CO2nchbYEc3X3J6WrmTTDto7yMPqVSZTUyY5Tjbid+Ab8gLnATtygYtiDIJGQRRn2ZOiA==";
      };
    };
    "lodash-es-4.17.21" = {
      name = "lodash-es";
      packageName = "lodash-es";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash-es/-/lodash-es-4.17.21.tgz";
        sha512 = "mKnC+QJ9pWVzv+C4/U3rRsHapFfHvQFoFB92e52xeyGMcX6/OlIl78je1u8vePzYZSkkogMPJ2yjxxsb89cxyw==";
      };
    };
    "magic-string-0.30.4" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.30.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.30.4.tgz";
        sha512 = "Q/TKtsC5BPm0kGqgBIF9oXAs/xEf2vRKiIB4wCRQTJOQIByZ1d+NnUOotvJOvNpi5RNIgVOMC3pOuaP1ZTDlVg==";
      };
    };
    "mdn-data-2.0.30" = {
      name = "mdn-data";
      packageName = "mdn-data";
      version = "2.0.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.30.tgz";
        sha512 = "GaqWWShW4kv/G9IEucWScBx9G1/vsFZZJUO+tD26M8J8z3Kw5RDQjaoZe03YAClgeS/SWPOcb4nkFBTEi5DUEA==";
      };
    };
    "periscopic-3.1.0" = {
      name = "periscopic";
      packageName = "periscopic";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/periscopic/-/periscopic-3.1.0.tgz";
        sha512 = "vKiQ8RRtkl9P+r/+oefh25C3fhybptkHKCZSPlcXiJux2tJF55GnEj3BVn4A5gKfq9NWWXXrxkHBwVPUfH0opw==";
      };
    };
    "prettier-3.0.3" = {
      name = "prettier";
      packageName = "prettier";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-3.0.3.tgz";
        sha512 = "L/4pUDMxcNa8R/EthV08Zt42WBO4h1rarVtK0K+QJG0X187OLo7l699jWw0GKuwzkPQ//jMFA/8Xm6Fh3J/DAg==";
      };
    };
    "regexp-to-ast-0.5.0" = {
      name = "regexp-to-ast";
      packageName = "regexp-to-ast";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp-to-ast/-/regexp-to-ast-0.5.0.tgz";
        sha512 = "tlbJqcMHnPKI9zSrystikWKwHkBqu2a/Sgw01h3zFjvYrMxEDYHzzoMZnUrbIfpTFEsoRnnviOXNCzFiSc54Qw==";
      };
    };
    "source-map-js-1.0.2" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.0.2.tgz";
        sha512 = "R0XvVJ9WusLiqTCEiGCmICCMplcCkIwwR11mOSD9CR5u+IXYdiseeEuXCVAjS54zqwkLcPNnmU4OeJ6tUrWhDw==";
      };
    };
    "svelte-4.2.1" = {
      name = "svelte";
      packageName = "svelte";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte/-/svelte-4.2.1.tgz";
        sha512 = "LpLqY2Jr7cRxkrTc796/AaaoMLF/1ax7cto8Ot76wrvKQhrPmZ0JgajiWPmg9mTSDqO16SSLiD17r9MsvAPTmw==";
      };
    };
  };
in
{
  prettier = nodeEnv.buildNodePackage {
    name = "prettier";
    packageName = "prettier";
    version = "3.0.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier/-/prettier-3.0.3.tgz";
      sha512 = "L/4pUDMxcNa8R/EthV08Zt42WBO4h1rarVtK0K+QJG0X187OLo7l699jWw0GKuwzkPQ//jMFA/8Xm6Fh3J/DAg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier is an opinionated code formatter";
      homepage = "https://prettier.io";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-svelte = nodeEnv.buildNodePackage {
    name = "prettier-plugin-svelte";
    packageName = "prettier-plugin-svelte";
    version = "3.0.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-svelte/-/prettier-plugin-svelte-3.0.3.tgz";
      sha512 = "dLhieh4obJEK1hnZ6koxF+tMUrZbV5YGvRpf2+OADyanjya5j0z1Llo8iGwiHmFWZVG/hLEw/AJD5chXd9r3XA==";
    };
    dependencies = [
      sources."@ampproject/remapping-2.2.1"
      sources."@jridgewell/gen-mapping-0.3.3"
      sources."@jridgewell/resolve-uri-3.1.1"
      sources."@jridgewell/set-array-1.1.2"
      sources."@jridgewell/sourcemap-codec-1.4.15"
      sources."@jridgewell/trace-mapping-0.3.19"
      sources."@types/estree-1.0.2"
      sources."acorn-8.10.0"
      sources."aria-query-5.3.0"
      sources."axobject-query-3.2.1"
      sources."code-red-1.0.4"
      sources."css-tree-2.3.1"
      sources."dequal-2.0.3"
      sources."estree-walker-3.0.3"
      sources."is-reference-3.0.2"
      sources."locate-character-3.0.0"
      sources."magic-string-0.30.4"
      sources."mdn-data-2.0.30"
      sources."periscopic-3.1.0"
      sources."prettier-3.0.3"
      sources."source-map-js-1.0.2"
      sources."svelte-4.2.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Svelte plugin for prettier";
      homepage = "https://github.com/sveltejs/prettier-plugin-svelte#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-toml = nodeEnv.buildNodePackage {
    name = "prettier-plugin-toml";
    packageName = "prettier-plugin-toml";
    version = "1.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-toml/-/prettier-plugin-toml-1.0.0.tgz";
      sha512 = "YMn4Fqy/ANHommZh61s5qqtpfcgPB00Ty890bFPr73B0HAy77zgyH89SvAK+NyPPx3AdM56a4Yo66LH9GPnuZw==";
    };
    dependencies = [
      sources."@chevrotain/cst-dts-gen-11.0.3"
      sources."@chevrotain/gast-11.0.3"
      sources."@chevrotain/regexp-to-ast-11.0.3"
      sources."@chevrotain/types-11.0.3"
      sources."@chevrotain/utils-11.0.3"
      sources."@toml-tools/lexer-1.0.0"
      sources."@toml-tools/parser-1.0.0"
      sources."chevrotain-11.0.3"
      sources."lodash-es-4.17.21"
      sources."prettier-3.0.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "TOML Prettier Plugin";
      homepage = "https://github.com/un-ts/toml-tools/tree/master#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@prettier/plugin-xml" = nodeEnv.buildNodePackage {
    name = "_at_prettier_slash_plugin-xml";
    packageName = "@prettier/plugin-xml";
    version = "3.2.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/@prettier/plugin-xml/-/plugin-xml-3.2.1.tgz";
      sha512 = "DvwnQPf8FsczapBVDm54IhR+Pryt3DbPZSNtUb9gOuFtgoUUPbPN69f3nQBMF5BEqh4ZjZjTaHBmsVno3UnAXQ==";
    };
    dependencies = [
      sources."@xml-tools/parser-1.0.11"
      sources."chevrotain-7.1.1"
      sources."prettier-3.0.3"
      sources."regexp-to-ast-0.5.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "prettier plugin for XML";
      homepage = "https://github.com/prettier/plugin-xml#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
