# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./lxd.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix
    ];

  users.users.enno = {
    uid = 502;
    extraGroups = [ "wheel" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/enno";
    homeMode = "700";
    useDefaultShell = true;
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Europe/Berlin";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
            -----BEGIN CERTIFICATE-----
      MIIDhjCCAm6gAwIBAgIUdxNI5UPwBgrGpKd98Bi1QTCOKHkwDQYJKoZIhvcNAQEL
      BQAwVDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRIwEAYDVQQHDAlTdW5ueXZh
      bGUxDTALBgNVBAoMBHhyZHAxFTATBgNVBAMMDHd3dy54cmRwLm9yZzAeFw0yMjA3
      MTIxNDQyMjVaFw0yMzA3MTIxNDQyMjVaMFQxCzAJBgNVBAYTAlVTMQswCQYDVQQI
      DAJDQTESMBAGA1UEBwwJU3Vubnl2YWxlMQ0wCwYDVQQKDAR4cmRwMRUwEwYDVQQD
      DAx3d3cueHJkcC5vcmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDD
      g/cRT99y7A9mZionFWFVYH3AivynX0I7dBJMs9i5GVk40Lrfrllmv+tzOYpGbATo
      j47px2m+PVd/B6rSneQEXYxAxSlSYwQonvlDA7vn/D+gUbdWIsXirRd87m48r/ef
      U+ZJVGMFnj4O5Sr3rVMgp9bpxSJJtLXuhJRfufgGZ96fhfaotB9PsVsHsVumSdHZ
      P6+WwPLvKgsuSYMqXEWyauUzdp0dKUqRQhVYgGB2qHrByeQuBVAT54RLF5i8yn62
      8nO9A9X0uJfdiRUwcBELz80miUkdgqcilETonGmXYqxgzMllkx9+YBKI9k4J9tby
      2HwkPu91XmvmMvSNEV0bAgMBAAGjUDBOMB0GA1UdDgQWBBQ6jNr/o4WJUI9tCNs0
      uqxzZ5AyBjAfBgNVHSMEGDAWgBQ6jNr/o4WJUI9tCNs0uqxzZ5AyBjAMBgNVHRME
      BTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBb9l7qXFibCGZE+pehtVK8j2dFXc8h
      hms7HK2Za58dzi04gduuN0G+QoijqZX91tWIU3lTydHghI5dzutLA6CS1O1AzptY
      rwYWX1Pij/PuJkyOXdSYb/uTEt21z42kl1TJCEBW+7AdFOlt0GAiHo+y3vf2nly3
      pyLbozClCmpmgDHsswKQ4l7bAU2Ltn1RJOVji2CE+Zw4d29t3sZrueGuPSaWDmTR
      LrOmzgAoxY3tVlioRFKZ637KONk3+D0XnUAaqwG/vUMmgz+9fqc8h9MUUF+sF3Nu
      nTDC/W09UrZA9NowJSjA5Q7tmBtAewSf8e19/9UYty0hIn0dxY9ouIR5
      -----END CERTIFICATE-----

      -----BEGIN CERTIFICATE-----
      MIICDDCCAbKgAwIBAgIQCdMDl5ylpkPD/YVlvrT/7jAKBggqhkjOPQQDAjBmMR0w
      GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
      cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
      IENBMB4XDTIzMTEyMDA4MjAxOFoXDTMzMTEyMDA4MjAxOFowZjEdMBsGA1UEChMU
      T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
      aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
      ByqGSM49AgEGCCqGSM49AwEHA0IABAQlDa5xB3xr5T85L8u8K4N6foZaKozNlTxb
      WQ8DYeSNdt6bqVQUgVBX0NJMxl77hV9+3fdAfzcGDNWzGrZjY+2jQjBAMA4GA1Ud
      DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTto9YC9WhdmcjO
      N6sNxDc1Nl6ABzAKBggqhkjOPQQDAgNIADBFAiEA/pKnKYJiol1vUYySdyYNAteU
      V8AIqsKP4Zv+XSBDbFgCIGUHqedMiJymNR+OqVu19n9uJBYPzOMoc8tra1Woe3Kl
      -----END CERTIFICATE-----

    ''
  ];

  system.stateVersion = "24.05"; # Did you read the comment?
}
