#!/usr/bin/env sh

set -e

WAVFILE=$(mktemp /tmp/wav.XXXXXX)
trap "rm -f $WAVFILE" EXIT

for video in "$@"; do
	ffmpeg -i "$video" -vn -acodec pcm_s16le -ac 1 -ar 16000 -f wav -y "$WAVFILE"
	whisper -t 10 -f "$WAVFILE" >"$video.txt"
done
